# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'vertx-ios-swift-client' do
    use_frameworks!
    inhibit_all_warnings!

    pod 'SwiftyJSON'
    pod 'BlueSocket'
end
